### Ejercicio: Datos climáticos estación

Link de datos: https://drive.google.com/drive/folders/1QD_GVY_KDRu6CEtN3qUmybuatw0WjRYx?usp=sharing


Crea un nuevo DataFrame con datos de 1 estaciones SENAMHI de diferentes regiones del Perú (https://www.senamhi.gob.pe/site/descarga-datos/).

Considerar lo siguiente a partir de "tutorial-para-la-descarga-de-datos.pdf".

Los datos de las columnas corresponden a:
- Columna A: Año
- Columna B: Mes
- Columna C: Día
- Columna D: Precipitación acumulada
- Columna E: Temperatura máxima
- Columna F: Temperatura mínima

En las celdas donde aparece -99.9 significa que no hay información disponible para esa variable

Luego:
1. Parsear el nombres de la estación Chosica y leer el archivo.
1. Calcula el promedio mensual de precipitación
1. Calcula el promedio anual de precipitación
2. Identifica el día más lluvioso
4. Exporta los resultados formateados en CSV

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [11]:
# Tu código aquí – Ejercicio: Estación

# Leer los datos de las estaciones y crear un DataFrame combinado
import os
files = os.listdir('/content/drive/MyDrive/SENAMHI')  # Lista los archivos en el directorio
files

['Copia de qc00151205_CANCHACALLA.txt',
 'Copia de qc00000543_ñaña.txt',
 'Copia de qc00155213_santa_eulalia.txt',
 'Copia de qc00151209_chosica.txt',
 'Copia de qc00155224_santiago_de_tuna.txt']

In [14]:
# Parsear el nombre del archivo para obtener el código y nombre de la estación
station = files[3]

codigo = station.replace('Copia de ', '').split('_')[0]
nombre = station.replace('Copia de ', '').split('_')[1].replace('.txt', '')

print(f"Código: {codigo}, Nombre: {nombre}")

Código: qc00151209, Nombre: chosica

In [16]:
# Leer el archivo CSV de la estación seleccionada
import pandas as pd
station_df = pd.read_table(f'/content/drive/MyDrive/SENAMHI/{station}', header=None, sep=' ', na_values=['-999','-99.9',"-3256"]) # Sin encabezados
# Formatear las columnas
station_df.columns = ['Año', 'Mes', 'Dia', 'Pr', 'Tmax', 'Tmin'] # Asignar nombres de columnas

station_df

       Año  Mes  Dia   Pr  Tmax  Tmin
0     1989   12    1  0.0   NaN   NaN
1     1989   12    2  0.0   NaN   NaN
2     1989   12    3  0.0   NaN   NaN
3     1989   12    4  0.0   NaN   NaN
4     1989   12    5  0.0   NaN   NaN
...    ...  ...  ...  ...   ...   ...
8823  2014    1   27  0.0   NaN   NaN
8824  2014    1   28  0.0   NaN   NaN
8825  2014    1   29  0.0   NaN   NaN
8826  2014    1   30  0.0   NaN   NaN
8827  2014    1   31  0.0   NaN   NaN

[8828 rows x 6 columns]

In [19]:
# Precipitacion mensual
precipitacion_mensual = station_df.groupby('Mes')['Pr'].mean()

# Precipitacion total anual
precipitacion_anual = station_df.groupby('Año')['Pr'].sum()

# Dia mas lluvioso
dia_mas_lluvioso = station_df.loc[station_df['Pr'].idxmax()]


print(f"Precipitación mensual:\n{precipitacion_mensual}\n")
print(f"Precipitación anual:\n{precipitacion_anual}\n")
print(f"El día más lluvioso fue el {dia_mas_lluvioso['Año']:.0f}-{dia_mas_lluvioso['Mes']:.0f}-{dia_mas_lluvioso['Dia']:.0f} con {dia_mas_lluvioso['Pr']} mm de precipitación.")

Precipitación mensual:
Mes
1     0.178629
2     0.307066
3     0.154278
4     0.084370
5     0.006732
6     0.000158
7     0.000840
8     0.000561
9     0.003184
10    0.004342
11    0.012899
12    0.044600
Name: Pr, dtype: float64

Precipitación anual:
Año
1989     0.0
1990    14.8
1991    14.0
1992     7.6
1993    14.6
1994    44.0
1995    19.6
1996    32.8
1997     0.9
1998    18.3
1999    39.6
2000    33.0
2001    25.7
2002    35.0
2003    21.5
2004     5.5
2005     5.9
2006    29.3
2007    15.7
2008    20.9
2009    51.9
2010     1.1
2011    23.8
2012    64.6
2013     7.1
2014     5.8
Name: Pr, dtype: float64

El día más lluvioso fue el 2012-4-4 con 37.0 mm de precipitación.

In [20]:
# Exportar los resultados formateados en CSV
precipitacion_mensual.to_csv('precipitacion_mensual_chosica.csv')
precipitacion_anual.to_csv('precipitacion_anual_chosica.csv')
dia_mas_lluvioso.to_frame().to_csv('dia_mas_lluvioso_chosica.csv')

print("Resultados exportados en CSV")

Resultados exportados en CSV

### Ejercicio 2: Datos climáticos multiestación

Crea un nuevo DataFrame con datos de 5 estaciones SENAMHI de diferentes regiones del Perú (https://www.senamhi.gob.pe/site/descarga-datos/).

Luego:
1. Paresear el nombres de la estaciones y leer los archivo.
1. Unir las db (Fecha, Est1, Est2, ...)
1. Calcula el promedio mensual de precipitación por región
2. Identifica el mes más lluvioso en cada estación
4. Exporta el resultado formateado a CSV

In [27]:
# Parsear los nombres de las estaciones
station1 = files[0]
station2 = files[1]
station3 = files[2]
station4 = files[3]
station5 = files[4]

In [22]:
# Leer los archivos
df1 = pd.read_table(f'/content/drive/MyDrive/SENAMHI/{station1}', header=None, sep=' ', na_values=['-999','-99.9','-3256'])
df2 = pd.read_table(f'/content/drive/MyDrive/SENAMHI/{station2}', header=None, sep=' ', na_values=['-999','-99.9','-3256'])
df3 = pd.read_table(f'/content/drive/MyDrive/SENAMHI/{station3}', header=None, sep=' ', na_values=['-999','-99.9','-3256'])
df4 = pd.read_table(f'/content/drive/MyDrive/SENAMHI/{station4}', header=None, sep=' ', na_values=['-999','-99.9','-3256'])
df5 = pd.read_table(f'/content/drive/MyDrive/SENAMHI/{station5}', header=None, sep=' ', na_values=['-999','-99.9','-3256'])

In [23]:
# Asignar nombres de columnas
df1.columns = ['Año','Mes','Dia','Pr','Tmax','Tmin']
df2.columns = ['Año','Mes','Dia','Pr','Tmax','Tmin']
df3.columns = ['Año','Mes','Dia','Pr','Tmax','Tmin']
df4.columns = ['Año','Mes','Dia','Pr','Tmax','Tmin']
df5.columns = ['Año','Mes','Dia','Pr','Tmax','Tmin']

In [28]:
# Crear nuevo DataFrame
df_multi = pd.DataFrame({ 'Est1': df1['Pr'], 'Est2': df2['Pr'], 'Est3': df3['Pr'], 'Est4': df4['Pr'], 'Est5': df5['Pr']})

df_multi

       Est1  Est2  Est3  Est4  Est5
0       0.0   0.0   0.0   0.0   NaN
1       8.0   0.0   0.0   0.0   NaN
2       0.0   0.0   0.0   0.0   NaN
3       0.0   0.0   0.0   0.0   NaN
4       0.0   0.0   0.2   0.0   NaN
...     ...   ...   ...   ...   ...
18320   NaN   NaN   0.0   NaN   0.0
18321   NaN   NaN   0.0   NaN   0.0
18322   NaN   NaN   0.0   NaN   0.0
18323   NaN   NaN   0.0   NaN   4.2
18324   NaN   NaN   0.0   NaN   1.7

[18325 rows x 5 columns]

In [34]:
# Crear la fecha
df1['Fecha'] = df1['Año'].astype(str) + '-' + df1['Mes'].astype(str) + '-' + df1['Dia'].astype(str)
df2['Fecha'] = df2['Año'].astype(str) + '-' + df2['Mes'].astype(str) + '-' + df2['Dia'].astype(str)
df3['Fecha'] = df3['Año'].astype(str) + '-' + df3['Mes'].astype(str) + '-' + df3['Dia'].astype(str)
df4['Fecha'] = df4['Año'].astype(str) + '-' + df4['Mes'].astype(str) + '-' + df4['Dia'].astype(str)
df5['Fecha'] = df5['Año'].astype(str) + '-' + df5['Mes'].astype(str) + '-' + df5['Dia'].astype(str)

In [35]:
# Poner Fecha como índice
df1 = df1.set_index('Fecha')
df2 = df2.set_index('Fecha')
df3 = df3.set_index('Fecha')
df4 = df4.set_index('Fecha')
df5 = df5.set_index('Fecha')

In [36]:
# Crear nuevo DataFrame
df_multi = pd.DataFrame({'Est1': df1['Pr'], 'Est2': df2['Pr'],   'Est3': df3['Pr'],  'Est4': df4['Pr'],  'Est5': df5['Pr']})

df_multi.index.name = 'Fecha'

df_multi

            Est1  Est2  Est3  Est4  Est5
Fecha
1963-12-1    NaN   NaN   0.0   NaN   NaN
1963-12-10   NaN   NaN   0.0   NaN   NaN
1963-12-11   NaN   NaN   0.0   NaN   NaN
1963-12-12   NaN   NaN   0.0   NaN   NaN
1963-12-13   NaN   NaN   0.0   NaN   NaN
...          ...   ...   ...   ...   ...
2014-1-5     0.0   0.0   0.0   0.0   0.0
2014-1-6     0.0   0.0   0.0   0.0   0.0
2014-1-7     1.0   0.0   0.0   1.4   0.0
2014-1-8     7.0   3.4   1.0   0.8   6.0
2014-1-9     1.9   0.0   0.7   0.0   2.3

[18325 rows x 5 columns]

In [42]:
# Promedio mensual de precipitación por estación
promedio1 = df1.groupby('Mes')['Pr'].mean()
promedio2 = df2.groupby('Mes')['Pr'].mean()
promedio3 = df3.groupby('Mes')['Pr'].mean()
promedio4 = df4.groupby('Mes')['Pr'].mean()
promedio5 = df5.groupby('Mes')['Pr'].mean()

print(f"Est1:\n{promedio1}\n")
print(f"Est2:\n{promedio2}\n")
print(f"Est3:\n{promedio3}\n")
print(f"Est4:\n{promedio4}\n")
print(f"Est5:\n{promedio5}\n")

Est1:
Mes
1     1.849940
2     3.080680
3     2.781514
4     0.555641
5     0.021712
6     0.000000
7     0.000000
8     0.000000
9     0.022667
10    0.210081
11    0.272400
12    1.125682
Name: Pr, dtype: float64

Est2:
Mes
1     0.026185
2     0.033954
3     0.020926
4     0.001027
5     0.000701
6     0.002687
7     0.001309
8     0.000726
9     0.000621
10    0.001466
11    0.001958
12    0.006381
Name: Pr, dtype: float64

Est3:
Mes
1     0.319776
2     0.543553
3     0.525434
4     0.022222
5     0.006583
6     0.000142
7     0.000000
8     0.001317
9     0.010278
10    0.023051
11    0.013830
12    0.109941
Name: Pr, dtype: float64

Est4:
Mes
1     0.178629
2     0.307066
3     0.154278
4     0.084370
5     0.006732
6     0.000158
7     0.000840
8     0.000561
9     0.003184
10    0.004342
11    0.012899
12    0.044600
Name: Pr, dtype: float64

Est5:
Mes
1     1.784516
2     3.439153
3     3.186570
4     0.567551
5     0.041677
6     0.000133
7     0.005097
8     0.002304
9     0.030284
10    0.110887
11    0.270136
12    0.962273
Name: Pr, dtype: float64

In [43]:
# Identificar el mes más lluvioso en cada estación
mes1 = promedio1.idxmax()
mes2 = promedio2.idxmax()
mes3 = promedio3.idxmax()
mes4 = promedio4.idxmax()
mes5 = promedio5.idxmax()

print(f"Est1: {mes1}")
print(f"Est2: {mes2}")
print(f"Est3: {mes3}")
print(f"Est4: {mes4}")
print(f"Est5: {mes5}")

Est1: 2
Est2: 2
Est3: 2
Est4: 2
Est5: 2

In [46]:
# Crear DataFrame con los promedios mensuales
resultado = pd.DataFrame({ 'Est1': promedio1, 'Est2': promedio2, 'Est3': promedio3,  'Est4': promedio4,  'Est5': promedio5})

resultado.index.name = 'Mes'

In [47]:
# Exportar resultados a CSV
df_multi.to_csv('datos_multiestacion.csv')
resultado.to_csv('promedio_mensual_multiestacion.csv')

print("Resultados exportados a CSV")

Resultados exportados a CSV